name: date_interval_navigator
description: Display a calendar view for flutter.
version: 0.0.1
author: Vinicius Andrade
homepage: https://github.com/vbandrade/date_interval_navigator

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: 0.15.7

dev_dependencies:
  flutter_test:
    sdk: flutter
